const initialState = {
	profile: {},
	apiCallstatus: {},
	ListUser:{},
	addStoreUser:{},
	addCustomStore:{},
	listStore:{},
	getStoreUserId:{},
	profileToken:{},
	addProductSuperAdmin:{},
	listSuperProductSuperAdmin:{},
	storeAdminLogin:{},
	addMenu:{},
	addProdcutToCustomStore:{},
	listStoreAdmin:{},
	editStore:{},
	editCustomStore:{},
	editStoreMenus:{},
	getProductidbyStoreAdmin:{},
	updateProductStoreAdmin:{},
	getSingleProductbySuperAdmin:{},
	editProductbySuperAdmin:{},
	OrderDetailSuperAdmin:{},
	OrderDetailStoreAdminId:{},
	listStoreMenus:{},
	addProductSubMenu:{},
	getStoreProductbyId:{},
	getMenuStoreById:{},
	addStudent:{},
	listAllRoles:{},
	addOffer:{},
	featureProduct:{},
	listOffer:{},
	updateOffer:{},
	getOfferid:{},
	listApproval:{},
	addApproval:{},
	updateApproval:{},
	updateOrder:{},
	dashboard:{}
};
export default initialState;
